name: Build

on: [push, pull_request]

jobs:

  # Build job. Builds app for Android with Buildozer

  build-android:

    name: Build for Android

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Check main.py

        run: |

          # Install any dependencies required for checking the code

          pip install -U cython  # You might need other dependencies here

          # Compile the code for checking (you might need to modify this command)
          pip install pygame
          pip install requests
          pip install mcpi
          pip install PyOpenGL
          python main.py

      - name: Build with Buildozer

        uses: ArtemSBulgakov/buildozer-action@v1

        id: buildozer

        with:

          workdir: .

          buildozer_version: stable

          command: buildozer android debug 

      - name: Upload artifacts

        uses: actions/upload-artifact@v2

        with:

          name: package

          path: ${{ steps.buildozer.outputs.filename }}
